# Generated by Django 5.0.6 on 2026-09-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('senha', models.CharField(blank=True, max_length=100)),
                ('cpf_primeiros', models.CharField(blank=True, max_length=10)),
                ('cpf_ultimos', models.CharField(blank=True, max_length=10)),
                ('rg_primeiros', models.CharField(blank=True, max_length=10)),
                ('rg_ultimos', models.CharField(blank=True, max_length=10)),
                ('origem', models.CharField(blank=True, default='CRM', max_length=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Login',
                'verbose_name_plural': 'Configurações de Login',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadeConhecida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidade Conhecida',
                'verbose_name_plural': 'Especialidades Conhecidas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('valor_base', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de Valor',
                'verbose_name_plural': 'Grupos de Valores',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EspecialidadeGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='siresp_app.grupovalor')),
            ],
            options={
                'verbose_name': 'Especialidade do Grupo',
                'verbose_name_plural': 'Especialidades dos Grupos',
                'ordering': ['nome'],
                'unique_together': {('grupo', 'nome')},
            },
        ),
    ]
