# Generated by Django 5.0.6 on 2026-09-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraMinuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional_norm', models.CharField(db_index=True, max_length=200)),
                ('especialidade_norm', models.CharField(db_index=True, max_length=200)),
                ('minutos', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Minuto',
                'verbose_name_plural': 'Regras de Minutos',
                'ordering': ['profissional_norm', 'especialidade_norm'],
                'unique_together': {('profissional_norm', 'especialidade_norm')},
            },
        ),
    ]
