# Generated by Django 5.0.6 on 2026-09-25 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0002_regraminuto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaologin',
            options={'verbose_name': 'Configuração de Login SIRESP', 'verbose_name_plural': 'Configurações de Login SIRESP'},
        ),
        migrations.AddField(
            model_name='configuracaologin',
            name='usuario_web',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_siresp', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Extracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_nome', models.CharField(max_length=200)),
                ('medico_crm', models.CharField(blank=True, max_length=50)),
                ('medico_codigo', models.CharField(blank=True, max_length=50)),
                ('data_ini', models.CharField(max_length=10)),
                ('data_fim', models.CharField(max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extração',
                'verbose_name_plural': 'Extrações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=300)),
                ('dados', models.JSONField(default=dict)),
                ('ordem', models.IntegerField(default=0)),
                ('extracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='siresp_app.extracao')),
            ],
            options={
                'verbose_name': 'Item de Produção',
                'verbose_name_plural': 'Itens de Produção',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SessaoSiresp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando login'), ('logado', 'Logado'), ('erro', 'Erro'), ('fechada', 'Fechada')], default='aguardando', max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('titulo_janela', models.CharField(blank=True, max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario_web', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessao_siresp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão SIRESP',
                'verbose_name_plural': 'Sessões SIRESP',
            },
        ),
    ]
