# Generated by Django 5.0.6 on 2026-09-28 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0003_alter_configuracaologin_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaologin',
            name='usuario_web',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_siresp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_total_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_total_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('extracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repasse', to='siresp_app.extracao')),
                ('usuario_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repasse',
                'verbose_name_plural': 'Repasses',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('especialidade', models.CharField(max_length=300)),
                ('oferta', models.IntegerField(default=0)),
                ('atendimentos', models.IntegerField(default=0)),
                ('minutos', models.DecimalField(decimal_places=2, default=15, max_digits=8)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_cheio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_percent', models.CharField(choices=[('0%', '0%'), ('50%', '50%'), ('100%', '100%')], default='100%', max_length=5)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grupo_nome', models.CharField(blank=True, max_length=200)),
                ('marcado', models.BooleanField(default=False)),
                ('faltou_regra', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('repasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='siresp_app.repasse')),
            ],
            options={
                'verbose_name': 'Item de Repasse',
                'verbose_name_plural': 'Itens de Repasse',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
