# Generated by Django 5.0.6 on 2026-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0004_alter_configuracaologin_usuario_web_repasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraminuto',
            name='bonus_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='regraminuto',
            name='valor_base_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repasse',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
