# Generated by Django 5.0.6 on 2026-09-30 14:29

from django.db import migrations, models


def popular_das_regras(apps, schema_editor):
    """Preenche a base com os profissionais das regras já importadas."""
    Regra = apps.get_model('siresp_app', 'RegraMinuto')
    Profissional = apps.get_model('siresp_app', 'Profissional')
    nomes = Regra.objects.values_list('profissional_norm', flat=True).distinct()
    for n in nomes:
        if n:
            Profissional.objects.get_or_create(nome_norm=n, defaults={'nome': n})


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0005_regraminuto_bonus_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_norm', models.CharField(db_index=True, max_length=200, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome_norm'],
            },
        ),
        migrations.RunPython(popular_das_regras, migrations.RunPython.noop),
    ]
