# Generated by Django 5.0.6 on 2026-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0006_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='competencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
