# Generated by Django 5.0.6 on 2026-09-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0007_repasse_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipe Médica',
                'verbose_name_plural': 'Equipes Médicas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='siresp_app.equipemedica'),
        ),
    ]
