# Generated by Django 5.0.6 on 2026-09-30 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0008_equipe_medica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('acao', models.CharField(db_index=True, max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('repasse_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('profissional', models.CharField(blank=True, db_index=True, max_length=200)),
                ('detalhes', models.JSONField(blank=True, default=list)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
