# Generated by Django 5.0.6 on 2026-09-30 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0009_log_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_nome', models.CharField(max_length=200)),
                ('nome_norm', models.CharField(db_index=True, max_length=200)),
                ('data_ini', models.CharField(max_length=10)),
                ('data_fim', models.CharField(max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sem_producao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta sem produção',
                'verbose_name_plural': 'Consultas sem produção',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario_web', 'nome_norm', 'data_ini', 'data_fim')},
            },
        ),
    ]
