# Generated by Django 5.0.6 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0010_sem_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaologin',
            name='unidade_preferida',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
