# Generated by Django 5.0.6 on 2026-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siresp_app', '0011_unidade_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracao',
            name='unidade_codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extracao',
            name='unidade_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
